[project]
name = "awake"
version = "0.1.0"
description = "Android Wiki of Attacks, Knowledge & Exploits"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-material>=9.7.1",
]
